URL_SERVICE = "https://cnt-aea6ba37-22a9-4456-afa6-57553717db7e.containerhub.tripleten-services.com"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"